# Generated by Django 6.0.3 on 2026-03-15 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='assignments',
        ),
    ]
